name: Test Site

on:
  pull_request:
    branches:
      - main

jobs: 
  test:
    runs-on: ubuntu-latest
    container: 
      image: node:20
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Lint CSS
        run: npm run lint:css

      - name: Lint JS
        run: npm run lint:js
